// Fake CLI agent for AgentSession integration tests. Simulates a Claude/Codex run inside a PTY:
// prints a readiness banner, waits for the instruction line (or a fallback timer), then behaves
// per --mode. Not a real agent; never imported by production code.
//
// Usage: node fake-cli.mjs --out <file> --marker <file> --mode <marker|team|exit|missing|idle|growing-idle|hang>
import { promises as fs } from 'node:fs';

function arg(name, def) {
  const i = process.argv.indexOf(name);
  return i >= 0 && process.argv[i + 1] !== undefined ? process.argv[i + 1] : def;
}

let out = arg('--out');
let marker = arg('--marker');
const mode = arg('--mode', 'marker');

process.stdout.write(`fake-cli ready: mode=${mode}\n`);

function delay(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

let acted = false;
async function hydrateFromInstruction(chunk) {
  if (out && marker) return;
  const text = String(chunk ?? '');
  const promptMatch = /read the file "([^"]+)"/i.exec(text);
  if (!promptMatch?.[1]) return;
  const prompt = await fs.readFile(promptMatch[1], 'utf8').catch(() => '');
  out ??= /Save your deliverable to exactly this file \(absolute path\):\s*\r?\n\s+([^\r\n]+)/.exec(prompt)?.[1]?.trim();
  marker ??= /write the single word "done" into it:\s*\r?\n\s+([^\r\n]+)/.exec(prompt)?.[1]?.trim();
}

async function act(chunk) {
  if (acted) return;
  acted = true;
  await hydrateFromInstruction(chunk);
  if (!out || !marker) {
    process.stderr.write('fake-cli missing output or marker path\n');
    process.exit(1);
  }
  if (mode === 'marker') {
    // Include both self-report tokens so this generic "completed" mode satisfies the semantic
    // completion gate for the execution (EXECUTION_RESULT) and review-fix (FIX_RESULT) stages.
    // Stages without a gate ignore these lines.
    await fs.writeFile(
      out,
      '# Output\n\nGenerated by fake-cli (with marker).\n\nEXECUTION_RESULT: done\nFIX_RESULT: fixed\n',
      'utf8',
    );
    await fs.writeFile(marker, 'done', 'utf8');
    process.exit(0);
  } else if (mode === 'team') {
    await fs.writeFile(
      out,
      [
        '```TeamMessage',
        JSON.stringify(
          {
            kind: 'chat',
            to: 'all',
            body: 'Fake team role turn completed.',
            taskId: 'TASK-FAKE',
          },
          null,
          2,
        ),
        '```',
        '',
      ].join('\n'),
      'utf8',
    );
    await fs.writeFile(marker, 'done', 'utf8');
    process.exit(0);
  } else if (mode === 'exit') {
    await fs.writeFile(out, '# Output\n\nGenerated by fake-cli (no marker, then exit).\n', 'utf8');
    process.exit(0);
  } else if (mode === 'missing') {
    process.exit(1); // exit without producing any output
  } else if (mode === 'idle') {
    await fs.writeFile(out, '# Output\n\nGenerated, then idle (no marker, no exit).\n', 'utf8');
    // stay alive, produce no further output
  } else if (mode === 'growing-idle') {
    // Keep appending to the output file for well over a second so an implementation WITHOUT a
    // stability gate (one that idle-completes on the first quiet poll with a non-empty file)
    // finishes mid-write and captures a partial file. The per-append gap (100ms) is deliberately
    // shorter than the test's doneIdleMs (300ms): a correct gate must keep waiting through every
    // append and only complete once the final write has stayed unchanged for doneIdleMs.
    await fs.writeFile(out, '# Output\n\npartial chunk 1\n', 'utf8');
    for (let i = 2; i <= 15; i += 1) {
      await delay(100);
      await fs.appendFile(out, `partial chunk ${i}\n`, 'utf8');
    }
    // The final write includes the execution self-report so this long-running mode satisfies the
    // semantic completion gate (the task completes `done`, not `blocked`). The `final chunk` line is
    // still the marker the stability test asserts on.
    await fs.appendFile(out, 'final chunk\nEXECUTION_RESULT: done\n', 'utf8');
    // stay alive, produce no further output
  } else {
    // 'hang': produce nothing and stay alive
  }
}

// team-loop: a PERSISTENT session — re-derive the output/marker paths from EACH
// instruction's prompt file and write them, without exiting, so one CLI can serve
// many prompts (exercises RoleCliSession's reuse across turns).
async function actLoop(text) {
  const promptMatch = /read the file "([^"]+)"/i.exec(text);
  if (!promptMatch?.[1]) return;
  const prompt = await fs.readFile(promptMatch[1], 'utf8').catch(() => '');
  const o = /Save your deliverable to exactly this file \(absolute path\):\s*\r?\n\s+([^\r\n]+)/.exec(prompt)?.[1]?.trim();
  const m = /write the single word "done" into it:\s*\r?\n\s+([^\r\n]+)/.exec(prompt)?.[1]?.trim();
  if (!o || !m) return;
  await fs.writeFile(
    o,
    ['```TeamMessage', JSON.stringify({ kind: 'chat', to: 'all', body: 'Fake persistent turn done.' }), '```', ''].join('\n'),
    'utf8',
  );
  await fs.writeFile(m, 'done', 'utf8');
  // stay alive for the next prompt
}

let triggered = false;
process.stdin.on('data', (chunk) => {
  if (mode === 'team-loop') {
    void actLoop(String(chunk ?? ''));
    return;
  }
  if (!triggered) {
    if ((!out || !marker) && !/read the file "/i.test(String(chunk ?? ''))) return;
    triggered = true;
    void act(chunk);
  }
});
// Fallback so the harness still acts if PTY stdin delivery is delayed.
setTimeout(() => {
  if (!triggered && out && marker) {
    triggered = true;
    void act();
  }
}, 1200);
// Keep the process alive for idle/hang modes.
setInterval(() => {}, 1 << 30);
