// Fake CLI agent for AgentSession integration tests. Simulates a Claude/Codex run inside a PTY:
// prints a readiness banner, waits for the instruction line (or a fallback timer), then behaves
// per --mode. Not a real agent; never imported by production code.
//
// Usage: node fake-cli.mjs --out <file> --marker <file> --mode <marker|exit|missing|idle|hang>
import { promises as fs } from 'node:fs';

function arg(name, def) {
  const i = process.argv.indexOf(name);
  return i >= 0 && process.argv[i + 1] !== undefined ? process.argv[i + 1] : def;
}

const out = arg('--out');
const marker = arg('--marker');
const mode = arg('--mode', 'marker');

process.stdout.write(`fake-cli ready: mode=${mode}\n`);

let acted = false;
async function act() {
  if (acted) return;
  acted = true;
  if (mode === 'marker') {
    await fs.writeFile(out, '# Output\n\nGenerated by fake-cli (with marker).\n', 'utf8');
    await fs.writeFile(marker, 'done', 'utf8');
    process.exit(0);
  } else if (mode === 'exit') {
    await fs.writeFile(out, '# Output\n\nGenerated by fake-cli (no marker, then exit).\n', 'utf8');
    process.exit(0);
  } else if (mode === 'missing') {
    process.exit(1); // exit without producing any output
  } else if (mode === 'idle') {
    await fs.writeFile(out, '# Output\n\nGenerated, then idle (no marker, no exit).\n', 'utf8');
    // stay alive, produce no further output
  } else {
    // 'hang': produce nothing and stay alive
  }
}

let triggered = false;
process.stdin.on('data', () => {
  if (!triggered) {
    triggered = true;
    void act();
  }
});
// Fallback so the harness still acts if PTY stdin delivery is delayed.
setTimeout(() => {
  if (!triggered) {
    triggered = true;
    void act();
  }
}, 1200);
// Keep the process alive for idle/hang modes.
setInterval(() => {}, 1 << 30);
