// ---------------------------------------------------------------------------
// Migration SQL for tables created by the retired v1 engines (Team role-chat,
// Tiger staged pipeline). The engines are gone (superseded by the v2 run
// engine - docs/REDESIGN.md), but the schema history must remain replayable on
// fresh databases, so their migration steps live on here verbatim (serialized
// from the original modules at removal time). Never edit applied migrations.
// ---------------------------------------------------------------------------

export interface LegacyMigration {
  id: string;
  statements: string[];
}

export const EXECUTION_CHECKPOINT_MIGRATION: LegacyMigration = {
  id: '20260618_tiger_execution_checkpoints',
  statements: [
    'CREATE TABLE IF NOT EXISTS execution_runs (\n    id VARCHAR(64) NOT NULL PRIMARY KEY,\n    workspace_path VARCHAR(1024) NOT NULL,\n    tiger_root VARCHAR(1024) NOT NULL,\n    owner_type VARCHAR(32) NOT NULL,\n    owner_id VARCHAR(191) NOT NULL,\n    status VARCHAR(32) NOT NULL,\n    attempts INT NOT NULL DEFAULT 1,\n    lease_owner VARCHAR(191) NULL,\n    lease_expires_at DATETIME(3) NULL,\n    started_at DATETIME(3) NULL,\n    ended_at DATETIME(3) NULL,\n    last_error TEXT NULL,\n    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),\n    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),\n    INDEX idx_execution_runs_workspace_status (workspace_path(191), status),\n    INDEX idx_execution_runs_lease (lease_owner, lease_expires_at)\n  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci',
    'CREATE TABLE IF NOT EXISTS run_stages (\n    id VARCHAR(128) NOT NULL PRIMARY KEY,\n    workspace_path VARCHAR(1024) NOT NULL,\n    run_id VARCHAR(64) NOT NULL,\n    stage_id VARCHAR(64) NOT NULL,\n    status VARCHAR(32) NOT NULL,\n    attempts INT NOT NULL DEFAULT 0,\n    config_json JSON NULL,\n    message TEXT NULL,\n    lease_owner VARCHAR(191) NULL,\n    lease_expires_at DATETIME(3) NULL,\n    started_at DATETIME(3) NULL,\n    ended_at DATETIME(3) NULL,\n    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),\n    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),\n    INDEX idx_run_stages_workspace_stage (workspace_path(191), stage_id),\n    INDEX idx_run_stages_run (run_id),\n    CONSTRAINT fk_run_stages_run FOREIGN KEY (run_id) REFERENCES execution_runs(id) ON DELETE CASCADE\n  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci',
    'CREATE TABLE IF NOT EXISTS agent_runs (\n    id VARCHAR(64) NOT NULL PRIMARY KEY,\n    workspace_path VARCHAR(1024) NOT NULL,\n    run_id VARCHAR(64) NOT NULL,\n    stage_id VARCHAR(64) NOT NULL,\n    terminal_id VARCHAR(64) NOT NULL,\n    agent_type VARCHAR(16) NOT NULL,\n    agent_index INT NOT NULL,\n    label VARCHAR(64) NOT NULL,\n    task_id VARCHAR(128) NULL,\n    status VARCHAR(32) NOT NULL,\n    command_text TEXT NOT NULL,\n    output_path VARCHAR(2048) NOT NULL,\n    output_rel VARCHAR(1024) NOT NULL,\n    marker_path VARCHAR(2048) NOT NULL,\n    prompt_path VARCHAR(2048) NOT NULL,\n    completion VARCHAR(32) NULL,\n    exit_code INT NULL,\n    error TEXT NULL,\n    attempts INT NOT NULL DEFAULT 0,\n    lease_owner VARCHAR(191) NULL,\n    lease_expires_at DATETIME(3) NULL,\n    started_at DATETIME(3) NULL,\n    ended_at DATETIME(3) NULL,\n    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),\n    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),\n    INDEX idx_agent_runs_workspace_stage (workspace_path(191), stage_id),\n    INDEX idx_agent_runs_run_stage (run_id, stage_id),\n    INDEX idx_agent_runs_task (workspace_path(191), task_id),\n    CONSTRAINT fk_agent_runs_run FOREIGN KEY (run_id) REFERENCES execution_runs(id) ON DELETE CASCADE\n  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci',
    'CREATE TABLE IF NOT EXISTS tasks (\n    workspace_path VARCHAR(1024) NOT NULL,\n    task_id VARCHAR(128) NOT NULL,\n    title TEXT NOT NULL,\n    execution_status VARCHAR(32) NOT NULL,\n    assigned_agent VARCHAR(128) NOT NULL,\n    review_status VARCHAR(32) NOT NULL,\n    review_notes TEXT NULL,\n    attempts INT NOT NULL DEFAULT 0,\n    lease_owner VARCHAR(191) NULL,\n    lease_expires_at DATETIME(3) NULL,\n    started_at DATETIME(3) NULL,\n    completed_at DATETIME(3) NULL,\n    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),\n    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),\n    PRIMARY KEY (workspace_path(191), task_id),\n    INDEX idx_tasks_status (workspace_path(191), execution_status),\n    INDEX idx_tasks_lease (lease_owner, lease_expires_at)\n  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci',
    'CREATE TABLE IF NOT EXISTS findings (\n    workspace_path VARCHAR(1024) NOT NULL,\n    finding_id VARCHAR(128) NOT NULL,\n    title TEXT NOT NULL,\n    related_task_id VARCHAR(128) NULL,\n    status VARCHAR(32) NOT NULL,\n    attempts INT NOT NULL DEFAULT 0,\n    lease_owner VARCHAR(191) NULL,\n    lease_expires_at DATETIME(3) NULL,\n    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),\n    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),\n    PRIMARY KEY (workspace_path(191), finding_id),\n    INDEX idx_findings_status (workspace_path(191), status),\n    INDEX idx_findings_lease (lease_owner, lease_expires_at)\n  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci',
    'CREATE TABLE IF NOT EXISTS artifacts (\n    id VARCHAR(64) NOT NULL PRIMARY KEY,\n    workspace_path VARCHAR(1024) NOT NULL,\n    run_id VARCHAR(64) NOT NULL,\n    stage_id VARCHAR(64) NOT NULL,\n    agent_run_id VARCHAR(64) NULL,\n    kind VARCHAR(64) NOT NULL,\n    abs_path VARCHAR(2048) NOT NULL,\n    rel_path VARCHAR(1024) NOT NULL,\n    checksum_sha256 CHAR(64) NULL,\n    size_bytes BIGINT NULL,\n    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),\n    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),\n    INDEX idx_artifacts_workspace_stage (workspace_path(191), stage_id),\n    INDEX idx_artifacts_run (run_id),\n    INDEX idx_artifacts_agent (agent_run_id),\n    CONSTRAINT fk_artifacts_run FOREIGN KEY (run_id) REFERENCES execution_runs(id) ON DELETE CASCADE\n  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci',
  ],
};

export const EXECUTION_WORKSPACE_LEASE_MIGRATION: LegacyMigration = {
  id: '20260618_tiger_execution_workspace_leases',
  statements: [
    'CREATE TABLE IF NOT EXISTS execution_workspace_leases (\n  workspace_hash CHAR(64) NOT NULL PRIMARY KEY,\n  workspace_path VARCHAR(1024) NOT NULL,\n  run_id VARCHAR(64) NULL,\n  lease_owner VARCHAR(191) NULL,\n  lease_expires_at DATETIME(3) NULL,\n  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),\n  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),\n  INDEX idx_execution_workspace_leases_path (workspace_path(191)),\n  INDEX idx_execution_workspace_leases_run (run_id),\n  CONSTRAINT fk_execution_workspace_leases_run FOREIGN KEY (run_id) REFERENCES execution_runs(id) ON DELETE SET NULL\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci',
  ],
};

export const TEAM_MIGRATION: LegacyMigration = {
  id: '20260618_team_runs',
  statements: [
    "CREATE TABLE IF NOT EXISTS team_runs (\n    id VARCHAR(64) NOT NULL PRIMARY KEY,\n    workspace_path VARCHAR(1024) NOT NULL,\n    tiger_root VARCHAR(1024) NOT NULL,\n    template_id VARCHAR(64) NULL,\n    goal MEDIUMTEXT NULL,\n    status VARCHAR(32) NOT NULL DEFAULT 'running',\n    owner_type VARCHAR(32) NOT NULL,\n    owner_id VARCHAR(191) NOT NULL,\n    attempts INT NOT NULL DEFAULT 1,\n    lease_owner VARCHAR(191) NULL,\n    lease_expires_at DATETIME(3) NULL,\n    seq_cursor BIGINT NOT NULL DEFAULT 0,\n    started_at DATETIME(3) NULL,\n    ended_at DATETIME(3) NULL,\n    last_error TEXT NULL,\n    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),\n    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),\n    INDEX idx_team_runs_workspace_status (workspace_path(191), status),\n    INDEX idx_team_runs_lease (lease_owner, lease_expires_at)\n  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
    "CREATE TABLE IF NOT EXISTS team_roles (\n    id VARCHAR(255) NOT NULL PRIMARY KEY,\n    run_id VARCHAR(64) NOT NULL,\n    role_key VARCHAR(128) NOT NULL,\n    name VARCHAR(191) NOT NULL,\n    agent_type VARCHAR(16) NOT NULL,\n    model VARCHAR(128) NULL,\n    effort VARCHAR(32) NULL,\n    permission VARCHAR(64) NULL,\n    can_write_code TINYINT(1) NOT NULL DEFAULT 0,\n    required_for_signoff TINYINT(1) NOT NULL DEFAULT 0,\n    status VARCHAR(32) NOT NULL DEFAULT 'idle',\n    system_prompt MEDIUMTEXT NULL,\n    terminal_id VARCHAR(64) NULL,\n    config_json JSON NULL,\n    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),\n    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),\n    UNIQUE KEY uq_team_roles_run_role (run_id, role_key),\n    INDEX idx_team_roles_run (run_id),\n    CONSTRAINT fk_team_roles_run FOREIGN KEY (run_id) REFERENCES team_runs(id) ON DELETE CASCADE\n  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
    'CREATE TABLE IF NOT EXISTS team_messages (\n    id VARCHAR(64) NOT NULL PRIMARY KEY,\n    run_id VARCHAR(64) NOT NULL,\n    seq BIGINT NOT NULL,\n    turn_id VARCHAR(64) NULL,\n    from_kind VARCHAR(16) NOT NULL,\n    from_role VARCHAR(128) NULL,\n    to_role VARCHAR(128) NULL,\n    channel VARCHAR(64) NULL,\n    kind VARCHAR(32) NOT NULL,\n    body MEDIUMTEXT NOT NULL,\n    refs_json JSON NULL,\n    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),\n    UNIQUE KEY uq_team_messages_run_seq (run_id, seq),\n    INDEX idx_team_messages_run_seq (run_id, seq),\n    INDEX idx_team_messages_turn (turn_id),\n    CONSTRAINT fk_team_messages_run FOREIGN KEY (run_id) REFERENCES team_runs(id) ON DELETE CASCADE\n  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci',
    'CREATE TABLE IF NOT EXISTS team_turns (\n    id VARCHAR(64) NOT NULL PRIMARY KEY,\n    run_id VARCHAR(64) NOT NULL,\n    role_key VARCHAR(128) NULL,\n    ordinal INT NOT NULL DEFAULT 0,\n    status VARCHAR(32) NOT NULL,\n    prompt_path VARCHAR(2048) NULL,\n    output_path VARCHAR(2048) NULL,\n    marker_path VARCHAR(2048) NULL,\n    error TEXT NULL,\n    started_at DATETIME(3) NULL,\n    ended_at DATETIME(3) NULL,\n    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),\n    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),\n    INDEX idx_team_turns_run (run_id, ordinal),\n    CONSTRAINT fk_team_turns_run FOREIGN KEY (run_id) REFERENCES team_runs(id) ON DELETE CASCADE\n  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci',
    "CREATE TABLE IF NOT EXISTS team_directives (\n    id VARCHAR(64) NOT NULL PRIMARY KEY,\n    run_id VARCHAR(64) NOT NULL,\n    target_role VARCHAR(128) NULL,\n    body MEDIUMTEXT NOT NULL,\n    status VARCHAR(32) NOT NULL DEFAULT 'pending',\n    delivered_at DATETIME(3) NULL,\n    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),\n    INDEX idx_team_directives_run (run_id, created_at),\n    CONSTRAINT fk_team_directives_run FOREIGN KEY (run_id) REFERENCES team_runs(id) ON DELETE CASCADE\n  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
    'CREATE TABLE IF NOT EXISTS team_signoffs (\n    run_id VARCHAR(64) NOT NULL,\n    role_key VARCHAR(128) NOT NULL,\n    signed_off TINYINT(1) NOT NULL DEFAULT 1,\n    summary MEDIUMTEXT NULL,\n    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),\n    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),\n    PRIMARY KEY (run_id, role_key),\n    INDEX idx_team_signoffs_run (run_id),\n    CONSTRAINT fk_team_signoffs_run FOREIGN KEY (run_id) REFERENCES team_runs(id) ON DELETE CASCADE\n  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci',
    'CREATE TABLE IF NOT EXISTS team_verifications (\n    id VARCHAR(64) NOT NULL PRIMARY KEY,\n    run_id VARCHAR(64) NOT NULL,\n    role_key VARCHAR(128) NULL,\n    kind VARCHAR(64) NULL,\n    passed TINYINT(1) NOT NULL DEFAULT 0,\n    summary MEDIUMTEXT NULL,\n    details_json JSON NULL,\n    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),\n    INDEX idx_team_verifications_run (run_id, created_at),\n    CONSTRAINT fk_team_verifications_run FOREIGN KEY (run_id) REFERENCES team_runs(id) ON DELETE CASCADE\n  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci',
    "CREATE TABLE IF NOT EXISTS team_templates (\n    id VARCHAR(64) NOT NULL PRIMARY KEY,\n    name VARCHAR(191) NOT NULL,\n    description TEXT NULL,\n    kind VARCHAR(16) NOT NULL DEFAULT 'team',\n    definition_json JSON NOT NULL,\n    builtin TINYINT(1) NOT NULL DEFAULT 0,\n    version INT NOT NULL DEFAULT 1,\n    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),\n    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),\n    archived_at DATETIME(3) NULL,\n    UNIQUE KEY uq_team_templates_name (name),\n    INDEX idx_team_templates_kind (kind),\n    INDEX idx_team_templates_archived (archived_at)\n  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
  ],
};

export const TEAM_TEMPLATES_MIGRATION: LegacyMigration = {
  id: '20260618_team_templates_columns',
  statements: [
    'DROP TABLE IF EXISTS team_templates',
    "CREATE TABLE IF NOT EXISTS team_templates (\n    id VARCHAR(64) NOT NULL PRIMARY KEY,\n    name VARCHAR(191) NOT NULL,\n    description TEXT NULL,\n    roles_json JSON NOT NULL,\n    builtin TINYINT(1) NOT NULL DEFAULT 0,\n    version INT NOT NULL DEFAULT 1,\n    source_kind VARCHAR(32) NOT NULL DEFAULT 'custom',\n    source_key VARCHAR(512) NULL,\n    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),\n    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),\n    archived_at DATETIME(3) NULL,\n    UNIQUE KEY uq_team_templates_name (name),\n    UNIQUE KEY uq_team_templates_source_key (source_key),\n    INDEX idx_team_templates_archived (archived_at),\n    INDEX idx_team_templates_builtin (builtin)\n  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
  ],
};

export const TEAM_ATTEMPTS_MIGRATION: LegacyMigration = {
  id: '20260619_team_attempts',
  statements: [
    "CREATE TABLE IF NOT EXISTS team_attempts (\n    id VARCHAR(64) NOT NULL PRIMARY KEY,\n    run_id VARCHAR(64) NOT NULL,\n    attempt_number INT NOT NULL DEFAULT 1,\n    status VARCHAR(32) NOT NULL DEFAULT 'running',\n    branch VARCHAR(512) NULL,\n    base_ref VARCHAR(512) NULL,\n    workspace_path VARCHAR(1024) NULL,\n    summary_json JSON NULL,\n    started_at DATETIME(3) NULL,\n    completed_at DATETIME(3) NULL,\n    promoted_at DATETIME(3) NULL,\n    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),\n    UNIQUE KEY uq_team_attempts_run_number (run_id, attempt_number),\n    INDEX idx_team_attempts_run (run_id, attempt_number),\n    CONSTRAINT fk_team_attempts_run FOREIGN KEY (run_id) REFERENCES team_runs(id) ON DELETE CASCADE\n  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
  ],
};
